// The large vocabulary behind the "look up" path of the word decoder:
// SCOWL word tiers plus country and capital names, all lowercase. The data is
// generated by scripts/build-vocab.ts. It's loaded lazily (a separate ~800 KB
// chunk in the browser), so the page itself stays small.

let base: Map<string, number> | undefined; // word -> rank (lower = more likely to be wanted)

async function loadBase(): Promise<Map<string, number>> {
  if (!base) {
    const data = (await import("./generated/vocab.json")).default as { byRank: string[][] };
    const map = new Map<string, number>();
    data.byRank.forEach((words, r) => {
      for (const w of words) map.set(w, r);
    });
    base = map;
  }
  return base;
}

/** Start downloading the dictionary early (e.g. once a key is saved). */
export const preloadVocabulary = () => void loadBase();

export class Vocabulary {
  private ranked: [string, number][];

  static async create(contextText: string): Promise<Vocabulary> {
    return new Vocabulary(await loadBase(), contextText);
  }

  private constructor(base: Map<string, number>, contextText: string) {
    const all = new Map(base);
    for (const w of contextText.toLowerCase().match(/[a-z][a-z'-]*/g) ?? []) all.set(w, -1); // conversation words first
    this.ranked = [...all].sort((a, b) => a[1] - b[1] || a[0].length - b[0].length);
  }

  /** All words starting with `prefix`, best-ranked first, shorter first within a rank. */
  bucket(prefix: string): string[] {
    return this.ranked.filter(([w]) => w.startsWith(prefix)).map(([w]) => w);
  }
}
